spring.application.name=nd-lanches-api
# Servidor
server.port=8080

# Configuração do PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/ndlanches
spring.datasource.username=postgres
spring.datasource.password=postdba
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Console do H2 (Pode remover ou comentar, já que agora usa Postgres)
spring.h2.console.enabled=false